#MySQL DB Setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hobby_chain
    username: root
    password: 1234
  #devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  #RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: hobby.chain
      routing-key: #라우팅 키
      default-receive-queue: hobby.chain.queue

# Mapper Xml Location
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

hobby:
  chain:
    file:
      dir: /Users/mac/Desktop/imgDir

# Firebase Service
firebase:
  account:
    key:
      path: hobby-chain-firebase-adminsdk.json