#MySQL DB Setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hobby_chain
    username: root
    password: 1234
  #devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

# Mapper Xml Location
mybatis:
  mapper-locations: classpath:mappers/*.xml
