#MySQL DB Setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hobby_chain
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  #devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  #redis session
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  #object storage config
  config:
    import:
    - classpath:/application.yml
    - classpath:/application-aws.yml

# Mapper
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true